- packages/centreon-ui/src/Listing/index.tsx
Its about a  modification on property shortName by shortLabel who is false
> enh(UI): Remplace property shortName by shortLabel

- packages/centreon-ui/src/InputField/Select/Autocomplete/Connected/index.tsx
This fixes an issue preventig the Autocomplete (Connected) from triggering the infinite scroll
> fix(Autocomplete): Fix infinite scroll

- Jenkinsfile
Fixing the issue with quality gate timeout from sonarqube by querying sonarqube api directly and check the success status.
<h2> How this pull request can be tested ? </h2>
Launch pipeline on that PR
> fix(ci): manage Quality gate timeout

- packages/centreon-ui/src/Listing/Header/SortableCell/Content.tsx
This adds a tooltip for columns with a short label
> Enh(UI): Add tooltip for short label's column

- packages/ui-context/src/UserContext.ts
- packages/ui-context/src/index.ts
- packages/ui-context/src/types.ts
- packages/ui-context/src/useCloudServices.ts
This adds cloud services settings to the global context.
> enh(Context): Manage cloud services in the global context

- packages/ui-context/src/UserContext.ts
- packages/ui-context/src/types.ts
- packages/ui-context/src/useCloudServices.ts
This adds the state function to be able to the cloud services state on the context
> enh(Context/Cloud Services): Add state modifier for cloud services to the Context

- Jenkinsfile
- sonar-project.properties
simplify qg check after sonarqube migration
> fix(ci): simplify qg check after sonarqube migration

- packages/frontend-config/babel/index.js
- packages/frontend-config/webpack/patch/module.js
This adds babel plugins and the clean-webpack-plugin to the webpack module patch configuration
> enh(Configuration): Improve babel and webpack configurations

- packages/centreon-ui/src/SortableItems/SortableItem.tsx
- packages/centreon-ui/src/SortableItems/index.tsx
- packages/centreon-ui/src/index.ts
This fixes a memoization issue and fix a typo
> fix(SortableItems): Fix memo on SortableItems

- packages/frontend-config/jest/index.js
This adds 'jsdom' as testEnvironment
> chore(Jest): Provide testEnvironment

- packages/centreon-ui/src/Wizard/ActionsBar.tsx
This revamps action buttons to follows the Material Design convention
> enh(Wizard): Revamp action buttons layout

- packages/centreon-ui/src/ListingPage/index.tsx
This allows to customize the CSS page
> enh(Listing page): Add a prop to customize the CSS page

- packages/ui-context/src/UserContext.ts
- packages/ui-context/src/types.ts
This adds a prop to user context about export button status
> feat(UI/Context): Add export button prop to user context

- packages/centreon-ui/src/PopoverMenu/index.tsx
This renders ClickAwayListener component only when popover menu is displayed
> fix(PopoverMenu): Fix the close behavior in the PopoverMenu

- packages/centreon-ui/src/InputField/Select/Autocomplete/Connected/index.tsx
This adds a property for conditions request field
> enh(Connected Autocomplete): Add prop for conditions field

- packages/centreon-ui/src/api/buildListingEndpoint/models.ts
This fix a typing issue in conditions
> enh(API Parameters): Fix condition typing

- packages/ui-context/src/UserContext.ts
- packages/ui-context/src/index.ts
- packages/ui-context/src/types.ts
- packages/ui-context/src/useAcknowledgement.ts
This adds acknowledgement parameters to the context
> enh(Context): Add acknowledgement to the context

- packages/frontend-config/webpack/base/index.js
This disabled the parser for systemJS
> enh(Webpack/base): Disable parser for systemJS

- Jenkinsfile
- package.json
- packages/centreon-ui/package.json
- packages/frontend-config/package.json
- packages/ui-context/package.json
This fixes packages semver and the build pipeline
> fix(version): Fix package version and build

- Jenkinsfile
- sonar-project.properties
sources' tarball are generated after the SQ analysis.
Resulting in a flapping QG.
Linked to https://github.com/centreon/centreon-build/pull/713
Also:
- added a QG timeout
- version updated
> :construction: fix(chore): add mandatory sources to SQ

- packages/frontend-config/webpack/patch/module.js
This adds Jotai to Webpack external modules
> enh(Config/Webpack): Add Jotai to Webpack externals

- packages/ui-context/src/defaults.ts
- packages/ui-context/src/types.ts
Add new property for Downtime in Context
> enh(UI): Add new property for Downtime in Context

- packages/ui-context/src/UserContext.ts
- packages/ui-context/src/types.ts
This adds new parameters to the downtime context
> enh(Context): Add new parameters to downtime

- package-lock.json
- package.json
- packages/centreon-ui/package-lock.json
- packages/centreon-ui/package.json
- packages/centreon-ui/src/Button/Save/StartIcon.tsx
This downgrade the Ramda typing library
> fix(Typings): Downgrade Ramda typing lib

- packages/centreon-ui/src/ListingPage/Filter.tsx
- packages/centreon-ui/src/ListingPage/FilterSkeleton.tsx
- packages/centreon-ui/src/ListingPage/ListingSkeleton.tsx
- packages/centreon-ui/src/ListingPage/index.tsx
This adds support of lazy loading on listing page and filter thanks to the Suspense component
> enh(Listing Page): Support lazy loading on listing page and filter

- packages/frontend-config/eslint/react/index.eslintrc.js
Fix path for centreon-frontend path
> fix(UI): Fix path for centreon-frontend path

- package-lock.json
- packages/centreon-ui/package.json
- packages/frontend-config/jest/index.js
Fix alias for jest into centreon-frontend
> fix(UI): Fix alias for jest into centreon-frontend

- package-lock.json
- packages/ui-context/src/defaults.ts
- packages/ui-context/src/types.ts
Remove prop default user waiting merged be into centreon
> fix(ui): Remove prop default user waiting merged be into centreon (PR #10507)

- packages/centreon-ui/src/Submenu/SubmenuHeader/index.tsx
Replace Header scss module with material makeStyles
> refactor(header): Replace Header scss module with material makeStyles

- packages/centreon-ui/src/MultiSelectEntries/index.tsx
adapt multi select entries to the dark mode colors
> refactor(style-MultiSelectEntries): adapt multi select entries to the dark mode colors

- packages/centreon-ui/src/Listing/Header/index.tsx
- packages/centreon-ui/src/ThemeProvider/index.tsx
centreon dark mode for resources status for listing page
> enh: centreon dark mode for resources status-listingPage component-

- packages/centreon-ui/src/Icon/IconHeader/index.tsx
- packages/centreon-ui/src/StatusCounter/index.tsx
- packages/centreon-ui/src/Submenu/SubmenuHeader/SubmenuItem/index.tsx
> enh: centreon dark mode for header

- packages/centreon-ui/src/utils/useLocaleDateTimeFormat/index.test.tsx
- packages/centreon-ui/src/utils/useLocaleDateTimeFormat/localeFallback.test.tsx
- packages/ui-context/src/defaults.ts
- packages/ui-context/src/types.ts
This adds `password_remaining_time` in the User context
> enh(Context): Add new prop in user context

- packages/centreon-ui/src/Dialog/index.tsx
> fix(Dialog): Fix Dialog scroll behaviour

- packages/centreon-ui/src/utils/useLocaleDateTimeFormat/index.ts
This fixes the time format for UTC and -1 timezone
> fix(UI): Fix time format

- packages/centreon-ui/src/StatusCounter/index.tsx
- packages/centreon-ui/src/Submenu/SubmenuHeader/index.tsx
> fix: header

- packages/centreon-ui/src/InputField/Select/Autocomplete/Draggable/SortableList.tsx
- packages/centreon-ui/src/SortableItems/index.tsx
This sends back the event provided by dnd-kit when drag ends
> enh(Sortable): Send back event from dnd-kit

- packages/ui-context/src/defaults.ts
- packages/ui-context/src/types.ts
> enh(UI): Add new prop to handle ACK

- packages/ui-context/src/defaults.ts
- packages/ui-context/src/types.ts
Remove option to force active check when set up acknowledgement
> fix(UI): Add option active_force_checks to acknowledge in user context

- packages/centreon-ui/src/Dialog/index.tsx
add ability to disable cancel button in dialog
> enh(entreon-map-NG): add the possibility to disable Cancel Button

- packages/ui-context/src/UserContext.ts
- packages/ui-context/src/index.ts
- packages/ui-context/src/types.ts
- packages/ui-context/src/useAcknowledgement.ts
Add 
hook for acknowledgement in user context
new props for acknowledgement
new props for downtime
> enh(ui) - Add acknowledgement in context

- packages/ui-context/src/UserContext.ts
- packages/ui-context/src/types.ts
Add use_deprecated_page in defaultUser and 
Add force_active_checks in ACK to context
> fix(UI): Re-add use_deprecated_page in defaultUser and add force_active_checks in ACK to context

- packages/frontend-config/eslint/base.eslintrc.js
- packages/frontend-config/eslint/react/index.eslintrc.js
move some eslint configuration to react specific eslint
> fix(eslintrc) : move hooks to react  configuration

- packages/centreon-ui/src/Listing/Header/SortableCell/Content.tsx
- packages/centreon-ui/src/Listing/Header/index.tsx
> fix(UI): Fix listing header background color

- packages/centreon-ui/src/MenuSkeleton/index.tsx
> enh(cenreonUi/MenuSkeleton):  header and menu skeleton creates an unstable UI

- packages/centreon-ui/src/ListingPage/index.tsx
this problem is already fixed in dev-21.10.x
> enh(develop): MAP NG viewer is now very small in size

- packages/centreon-ui/src/InputField/Select/Autocomplete/Multi/index.stories.tsx
- packages/centreon-ui/src/InputField/Select/Autocomplete/index.tsx
Add isNil funtion for the placeholder prop in autocomplete
> enh(UI): Add isNil funtion for the placeholder prop in autocomplete

- packages/centreon-ui/src/Dialog/index.tsx
<h2> How this pull request can be tested ? </h2>
Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.
Any **relevant details** of the configuration to perform the test should be added.
> enh(dialog): children prop is now optional

- Jenkinsfile
This fixes the Jenkinsfile serie.
<h2> How this pull request can be tested ? </h2>
Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.
Any **relevant details** of the configuration to perform the test should be added.
> fix(CI): Fix Jenkinsfile serie

- packages/centreon-ui/src/Form/Inputs/FieldsTable/Row.tsx
This fixes a layout issue for Safari
<h2> How this pull request can be tested ? </h2>
Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.
Any **relevant details** of the configuration to perform the test should be added.
> Fix(Form): Fix layout for Safari
